nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  # The plugin source file has to be present in the repository, otherwise it would have to be install
  # before running yarn install by the user/ci...
  - .yarn/plugins/plugin-after-install.js

afterInstall: yarn postinstall
