blank_issues_enabled: false
contact_links:
  - name: Join Sentry Discord
    url: https://discord.com/invite/sentry
    about: A place to talk about SDK development and other Sentry related topics. It's not meant as a support channel.
