require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'sample' do
  config = use_native_modules!
  use_react_native!(
    :path => config["reactNativePath"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
  	:hermes_enabled => false
  )

  pod 'RNSentry', :path => '../../RNSentry.podspec'

  target 'sampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'sample-tvOS' do
  # Pods for sample-tvOS

  target 'sample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
