require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.4'

target 'RNSentryCocoaTesterTests' do
  use_react_native!()
  pod 'RNSentry', :path => '../RNSentry.podspec'
end
