# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      # RNScreens and RNReanimated don't work when dynamically linked
      # Fix from https://github.com/software-mansion/react-native-screens/issues/1963#issuecomment-1848246731
      if pod.name.eql?('RNReanimated') || pod.name.eql?('RNScreens')
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
end

target 'sentryreactnativesample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  if ENV['RCT_NEW_ARCH_ENABLED'] == '1'
    pod 'AppTurboModules', :path => "./../tm"
  end

  target 'sentryreactnativesampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Disable SDK_V9 for Sentry when environment variable is set
    if ENV['SENTRY_DISABLE_SDK_V9']
      installer.pods_project.targets.each do |target|
        if target.name == 'Sentry'
          target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SDK_V9=0'
            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= ['$(inherited)']
            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'].delete('SDK_V9')
          end
        end
      end
    end
  end
end
