name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  danger:
    uses: lucas-zimerman/sentry-github-workflows/.github/workflows/danger.yml@lz/ext-danger
    with:
      extra-dangerfile: scripts/check-replay-stubs.js
# test6
