name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  danger:
    uses: getsentry/github-workflows/.github/workflows/danger.yml@v2

  # Check if replay-stubs.jar has changed
  replay-stubs-path-check:
    runs-on: ubuntu-latest
    outputs:
      replay-stubs-changed: ${{ steps.changes.outputs.replay-stubs-changed }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            replay-stubs-changed:
              - 'packages/core/android/libs/replay-stubs.jar'

  replay-stubs-check:
    runs-on: ubuntu-latest
    needs: [danger, replay-stubs-path-check]
    if: always() && needs.replay-stubs-path-check.outputs.replay-stubs-changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check Replay Stubs
        env:
          EXTRA_DANGERFILE: scripts/check-replay-stubs.js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lucas-zimerman/sentry-github-workflows/danger@lz/ext-danger
        with:
          api-token: ${{ secrets.GITHUB_TOKEN }}
          permissions: write


