name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review, labeled, unlabeled]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/danger@4013fc6e1aeb1be1f9d3b4d232624f0ec1afa613
        with:
          extra-dangerfile: scripts/check-additional-danger.js
          extra-install-packages: "curl unzip openjdk-17-jre-headless"
